name: terraform-deploy
run-name: ${{ github.actor }} is deploying terraform infrastructure
on:
  push:
    branches: [ test ] 
  workflow_dispatch:
jobs:
  terraform-test:
    name: Deploy TF
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
    - uses: actions/checkout@v3
      with:
        repository: nguyentan11/github-action
        ref: 'test'
    - name: Install dependencies
      run: |
        sudo apt update -y
        ls -al /usr/bin/python*
        python3 -m pip -V
        python3 -m pip install --user ansible-core==2.12.3
        ansible --version
        python3 -m pip install pywinrm
        ansible-galaxy collection install ansible.windows
        ansible-galaxy collection install community.windows
    - name: write inventory
      run: |
        echo [windows] > inventory
        echo 13.229.53.73 >> inventory
        echo [windows:vars] >> inventory
        echo ansible_user=localadmin >> inventory
        echo ansible_password=P@ssword01 >> inventory
        echo ansible_connection=winrm >> inventory
        echo ansible_winrm_server_cert_validation=ignore >> inventory
        echo ansible_port=5986 >> inventory
    - name: Test
      run: |
        export ANSIBLE_HOST_KEY_CHECKING=False
        cat Tan-TF-Windows-key
        cat inventory
        ansible -i inventory -m win_ping
