name: terraform-deploy
run-name: ${{ github.actor }} is deploying terraform infrastructure
on:
  push:
    branches: [ test ]
  workflow_dispatch:
jobs:
  terraform-test:
    name: Deploy TF
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
    - uses: actions/checkout@v3
      with:
        repository: nguyentan11/github-action
        ref: 'test'
    - name: Install dependencies
      run: |
        sudo apt update -y
        ls -al /usr/bin/python*
        python3 -m pip -V
        python3 -m pip install --user ansible-core==2.12.3
        ansible --version
        python3 -m pip install pywinrm
        ansible-galaxy collection install community.windows
        aws --version
        aws ssm get-parameter --name Tan-TF-Linux-key --query Parameter.Value > tmp1
        aws ssm get-parameter --name Tan-TF-Windows-key --query Parameter.Value > tmp2      
        cat tmp1 | sed 's/"//g' | tr -d "\n" > linux-key
        cat tmp2 | sed 's/"//g' | tr -d "\n" > windows-key
        echo "Linux Private key"
        cat linux-key
        chmod 400 linux-key
        echo "Windows Private key"
        cat windows-key
        ssh -i linux-key ec2-user@13.214.210.23 -o StrictHostKeyChecking=no
