name: terraform-deploy
run-name: ${{ github.actor }} is deploying terraform infrastructure
on:
  push:
    branches: [ test ] 
  workflow_dispatch:
jobs:
  terraform-test:
    name: Deploy TF
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
    - uses: actions/checkout@v3
      with:
        repository: nguyentan11/github-action
        ref: 'test'
    - name: Install dependencies
      run: |
        sudo apt install software-properties-common -y
        sudo apt-add-repository ppa:deadsnakes/ppa -y
        sudo apt-add-repository ppa:ansible/ansible -y
        sudo apt update -y
        sudo apt install python3 -y
        sudo apt install ansible -y
        sudo apt install python3-pip -y
        ls -al /usr/bin/python*
        ansible --version
        python3 --version
        pip3 --version
        . /opt/pipx/venvs/ansible-core/bin/activate && /opt/pipx/venvs/ansible-core/bin/python -m pip install pywinrm
    - name: Checkout Terraform repo
      uses: actions/checkout@v3
      with:
        repository: nguyentan11/fsoft-lab1
        ref: 'test'
    - name: Specific terraform version
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.9
        terraform_wrapper: false
    - name: Init TF
      run: terraform init
    - name: Apply TF
      run: terraform apply -auto-approve
    - name: Test
      run: |
        export ANSIBLE_HOST_KEY_CHECKING=False
        cat Tan-TF-Windows-key
        cat ansible-inventory/inventory
        ansible windows -i ansible-inventory/inventory -m win_ping
    - name: Destroy TF
      if: always()
      run: terraform destroy -auto-approve

        