name: terraform-deploy
run-name: ${{ github.actor }} is deploying terraform infrastructure
on:
  push:
    branches: [ test ] 
  workflow_dispatch:
jobs:
  terraform-test:
    name: Deploy TF
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
    - uses: actions/checkout@v3
      with:
        repository: nguyentan11/github-action
        ref: 'test'
    - name: Install dependencies
      run: |
        sudo apt purge --auto-remove python3
        sudo apt update -y
        sudo apt upgrade -y
        python3 -V
        sudo apt-add-repository ppa:ansible/ansible -y
        sudo apt update -y
        sudo apt install software-properties-common -y
        sudo apt install ansible -y
        ls /usr/bin/python*
        ansible --version
        python --version
        sudo find / -name win_ping.ps1
    