name: terraform-deploy
run-name: ${{ github.actor }} is deploying terraform infrastructure
on:
  push:
    branches: [ test ] 
  workflow_dispatch:
jobs:
  terraform-test:
    name: Deploy TF
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
    - uses: actions/checkout@v3
      with:
        repository: nguyentan11/github-action
        ref: 'test' 
    - name: Install Ansible
      run: |
        sudo apt-get update -y
        sudo apt install software-properties-common -y
        sudo add-apt-repository --yes --update ppa:ansible/ansible
        sudo apt install ansible -y
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        repository: nguyentan11/fsoft-lab1
        ref: 'test'
    - name: Specific terraform version
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.9
        terraform_wrapper: false
    - name: Init TF
      run: terraform init -lock=false
    - name: Apply TF
      run: terraform apply -auto-approve -lock=false
    - name: Create Ansible inventory
      run: |
        export ANSIBLE_HOST_KEY_CHECKING=False
        linux_private_key_pem=$(terraform output linux_private_key_pem)
        mkdir -p ~/.ssh
        echo $linux_private_key_pem > ~/.ssh/li_private_key.key
        chmod 400 ~/.ssh/li_private_key.key
        ls -al
        sudo chown -R runner:runner /etc/ansible
        echo [linux] >> /etc/ansible/hosts
        tempip=$(terraform output linux_public_ip)
        echo $tempip ansible_ssh_private_key_file=~/.ssh/li_private_key.key > tmp
        cat tmp | sed 's/"//g' >> /etc/ansible/hosts
        cat /etc/ansible/hosts
        ssh -V
        openssl version -a
        linuxip=`echo $tempip | sed 's/"//g'`
        sudo cat /etc/ssh/sshd_config | sudo sed 's/#GSSAPIAuthentication no/GSSAPIAuthentication no/g' > /etc/ssh/sshd_config
        sudo cat /etc/ssh/sshd_config
    - name: Destroy TF
      run: terraform destroy -auto-approve -lock=false
