name: terraform-deploy
run-name: ${{ github.actor }} is deploying terraform infrastructure
on:
  push:
    branches: [ test ] 
  workflow_dispatch:
jobs:
  terraform-test:
    name: Deploy TF
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
    - uses: actions/checkout@v3
      with:
        repository: nguyentan11/github-action
        ref: 'test'
    - name: Install dependencies
      run: |
        sudo apt update -y
        sudo apt remove --auto-remove python -y
        sudo apt purge --auto-remove python3-pip -y
        sudo add-apt-repository universe
        sudo apt install python2* -y
        ls /usr/bin/python*
        sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.7 0
        sudo update-alternatives --config python
        curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
        sudo python2 get-pip.py
        pip2 -V
        pip2 install pywinrm
        pip2 install ansible
        ansible --version
        python --version
    - name: Checkout Terraform repo
      uses: actions/checkout@v3
      with:
        repository: nguyentan11/fsoft-lab1
        ref: 'test'
    - name: Specific terraform version
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.9
        terraform_wrapper: false
    - name: Init TF
      run: terraform init
    - name: Apply TF
      run: terraform apply -auto-approve
    - name: Test
      run: |
        cat ansible-inventory/inventory
        ansible windows -vvv -i ansible-inventory/inventory -m win_ping
