name: terraform-deploy
run-name: ${{ github.actor }} is deploying terraform infrastructure
on:
  push:
    branches: [ test ] 
  workflow_dispatch:
jobs:
  terraform-test:
    name: Deploy TF
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
    - uses: actions/checkout@v3
      with:
        repository: nguyentan11/github-action
        ref: 'test'
    - name: Install Ansible and dependencies
      run: |
        sudo apt update -y
        sudo apt install software-properties-common -y
        sudo add-apt-repository --yes --update ppa:ansible/ansible
        sudo apt install ansible -y
        ansible-galaxy collection install ansible.windows
        ansible-galaxy collection install community.windows

    - name: Run Ansible playbook
      run: | 
        export ANSIBLE_HOST_KEY_CHECKING=False
        sudo chown -R runner:runner /etc/ansible
        echo [windows] >> /etc/ansible/hosts
        echo 13.212.4.245 >> /etc/ansible/hosts
        echo [windows:vars] >> /etc/ansible/hosts
        echo ansible_user=localadmin >> /etc/ansible/hosts
        echo ansible_password=P@ssword01 >> /etc/ansible/hosts
        echo ansible_connection=winrm >> /etc/ansible/hosts
        echo ansible_winrm_server_cert_validation=ignore >> /etc/ansible/hosts
        ansible windows -m ping