- name: New Relic setup
  hosts: linux
  tasks:
    - name: Ping check hosts
      ansible.builtin.ping:
    - name: Print message
      ansible.builtin.debug:
        msg: Able to connect host
    - name: add license key
      copy:
        dest: "/etc/newrelic-infra.yml"
        content: |
          license_key: e8633494910348db21863d93101da438ffc0NRAL
      become: true
      become_user: root
    - name: Add the infra monitoring agent repo
      command: curl -o /etc/yum.repos.d/newrelic-infra.repo https://download.newrelic.com/infrastructure_agent/linux/yum/amazonlinux/2/x86_64/newrelic-infra.repo
      become: true
      become_user: root
    - name: Enable repo newrelic
      ansible.builtin.yum:
        name: newrelic-infra
        enablerepo: "newrelic-infra"
      become: true
      become_user: root
    - name: Install New Relic agent
      ansible.builtin.yum:
        name: newrelic-infra
        state: present
      become: true
      become_user: root
    - name: Start New Relic agent
      command: systemctl restart newrelic-infra
      become: true
      become_user: root